name = "glerd_example"
version = "1.0.0"

description = "This is an example project to show how to use Glerd, a Gleam package that generates metadata for Records written in Gleam."
licences = ["MIT"]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
